apiVersion: v1
kind: Pod
metadata:
  name: secret-1401
spec:
  containers:
  - image: busybox
    name: busybox
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-7wlw4
      readOnly: true
  volumes:
  - name: default-token-7wlw4
    secret:
      defaultMode: 420
      secretName: default-token-7wlw4
status:
  phase: Pending
  qosClass: BestEffort
