apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"alpha-claim","namespace":"alpha"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"slow-storage","volumeMode":"Filesystem"}}
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  name: alpha-claim
  selfLink: /api/v1/namespaces/alpha/persistentvolumeclaims/alpha-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
  volumeMode: Filesystem
status: {}
